#!/bin/bash

#combine all the images into a gif and a mp4

# $2 is the name of the file, $1 is the images directory



ffmpeg_path=$(which ffmpeg)
$ffmpeg_path -f image2 -i $1/$2_%d.png gifs/$2.gif
$ffmpeg_path -f image2 -i $1/$2_%d.png -vcodec libx264 -s 500x500 -pix_fmt yuv420p movs/$2.mp4
cp $1/$2_0.png coverimages/$2.png
rm -f $1/$2_*
echo $3 > cdr-functions/$2.js